name: Automatic Artifacting
on: [push]
jobs:
  Curseforge-Like:
    runs-on: ubuntu-latest
    steps:
      - run: wget http://github.com/${{ github.event.repository.full_name }}/archive/${{ github.ref }}.tar.gz
      - run: tar -xvzf $(ls)
      - run: rm *.tar.gz
      - run: mv $(ls)/* .
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: .
